language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
 - composer install

script: php ./vendor/phpunit/phpunit/phpunit.php --bootstrap ./public/test.php ./tests/Tests/*


notifications:
  email:
    - gabrielmalet@gmail.com
