language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - ./tests/install-phalcon.sh
  - composer update --dev

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 libraries/ app/
  - php vendor/bin/phpunit --configuration tests/phpunit.xml