language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install php5-dev
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - composer update --dev

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 libraries/ app/
  - php vendor/bin/phpunit --configuration tests/phpunit.xml
